### ISSUE TITLE
Can't get to work on 335

### ISSUE THREAD

**Issue by SamiRayR** [BannZay/PlatesMaster#1]
Hi BannZay, I can't get PlatesMaster or PlatesClasses to work on 335. They do not show up in game but they do show up at the character selection screen's add on checklist. In game, they show up when I mouse over the latency bar when it displays the memory allocated to addons, but when I go to interface -> add ons, neither appear. Can you help?

**Comment by SamiRayR** [comment]
To add, I tried without any other  addons enabled - still did not work

**Comment by BannZay** [comment]
Hi, PlatesMaster is a quite an old addon and it does not have ingame UI settings, sorry. 

The fact that you have it listed in the menu means that you correctly installed it, just make sure that you have all its modules(i.e. PlatesMaster_of_ArenaPets which shows pets icons, PlatesMaster_of_Totems which shows totem icons, PlatesMaster_of_Purity which hides some insignificant nameplates like hunters snakes) enabled along with core addon (PlatesMaster).

The only way to configure it is to enable/disable addon modules.

But the other addon (PlatesClasses) is an addon which was based on this one, it has all feature of its predecessor and more. It also has UI ingame options.

I am gona check PlatesClasses shortly and confirm if it works correctly.

**Comment by BannZay** [comment]
PlatesClasses does work correctly for me. However if you use githubs "download zip" from code dropdown, then it wont work since github will not include submodules into archive. 

Thus, make sure you downloading released zip archive (like this https://github.com/BannZay/PlatesClasses/releases/download/1.1/PlatesClasses.zip).

You better should always download only releases if possible. If you really want to download full&latest but potentially unstable version of github repo, you have to download git client and use commands like following:
```
git clone  https://github.com/BannZay/PlatesClasses
cd PlatesClasses
git submodule update --init --recursive
```

P.s.: as of today for PlatesClasses you should just download release since I just made it from very last sources. Enjoy the addon!

**Comment by BannZay** [comment]
Closing for now. Please reopen this issue if you still have issues after using release version of the addon

**Comment by SamiRayR** [comment]
Thank you for your quick response and guidance, I will do as you suggest
and if anything else comes up will come back to you.

Would you be open to fielding more general questions about 335 UI/addons?
There are a number of UI features I would like to have, but haven't found
addons for yet. Is there a more appropriate place for these kinds of
questions, if you are open? With your permission, I will report your
answers back to the warmane forum as I think others would be interested
too, in the thread I started here:
https://forum.warmane.com/showthread.php?t=460851

I will soon add a clarification there about correctly installing
PlatesClasses and PlatesMaster's status.

**Comment by BannZay** [comment]
> Would you be open to fielding more general questions about 335 UI/addons?

I quit 3.3.5 since 3.4.x (aka oficial wotlk classic) available so I am not investing as much time in making addons for old wrath anymore. However, I have quite of an extensive knowledge about addons for 3.3.5 so I could be a good source of information and I dont mind to share it.

> Is there a more appropriate place for these kinds of questions, if you are open?

Yes, you can always try to reach me out in discord (same username as on github).

> With your permission, I will report your answers back to the warmane forum

Sure.
